spring:
  application:
    name: spring-cloud-eureka-4
  profiles: localhost4
  freemarker:
    prefer-file-system-access: false
server:
  port: 8004
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://localhost:${server.port}/eureka/