spring:
  application:
    name: spring-cloud-eureka-1
  profiles: localhost1
server:
  port: 8000
eureka:
  instance:
    hostname: localhost1
  client:
    serviceUrl:
      defaultZone: http://localhost2:8001/eureka/,http://localhost3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka-2
  profiles: localhost2
server:
  port: 8001
eureka:
  instance:
    hostname: localhost2
  client:
    serviceUrl:
      defaultZone: http://localhost1:8000/eureka/,http://localhost3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka-3
  profiles: localhost3
server:
  port: 8002
eureka:
  instance:
    hostname: localhost3
  client:
    serviceUrl:
      defaultZone: http://localhost1:8000/eureka/,http://localhost2:8001/eureka/
---
spring:
  application:
    name: spring-cloud-eureka-4
  profiles: localhost4
  freemarker:
    prefer-file-system-access: false
server:
  port: 8004
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://localhost:${server.port}/eureka/